name: Check latest commit is less than a day old

on:
  workflow_call:
    outputs:
      should_run:
        description: "Whether other jobs should run in a nightly release (false or empty)"
        value: ${{ jobs.should_run.outputs.should_run }}

jobs:
  should_run:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day old
        run: |
          git clone --no-checkout --depth=1 --filter=blob:none https://github.com/${{ github.repository }} lok
          cd lok
          test -z $(git rev-list  --after="24 hours" @) && echo "::set-output name=should_run::false" 
